export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS';

export const SHOW_ADD_COMPONENT = 'SHOW_ADD_COMPONENT';
export const SHOW_SETTING_COMPONENT = 'SHOW_SETTING_COMPONENT';
export const SHOW_PROFILE_SELECTOR = 'SHOW_PROFILE_SELECTOR';

export const SET_PROFILE_PICTIRE = 'SET_PROFILE_PICTIRE';
export const REMOVE_PROFILE_PICTIRE = 'REMOVE_PROFILE_PICTIRE';
